version: "3.8"

networks:
  kong-net:
    driver: bridge

services:

  kong-bootstrap:
    image: kong:3.6
    container_name: kong-bootstrap
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: host.docker.internal
      KONG_PG_PORT: 5432
      KONG_PG_DATABASE: kong
      KONG_PG_USER: postgres
      KONG_PG_PASSWORD: 1
    command: kong migrations bootstrap
    restart: on-failure

  kong-migrate:
    image: kong:3.6
    container_name: kong-migrate
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: host.docker.internal
      KONG_PG_PORT: 5432
      KONG_PG_DATABASE: kong
      KONG_PG_USER: postgres
      KONG_PG_PASSWORD: 1
    command: kong migrations up && kong migrations finish
    depends_on:
      kong-bootstrap:
        condition: service_completed_successfully
    restart: "no"

  kong:
    image: kong:3.6
    container_name: kong
    networks:
      - kong-net
    depends_on:
      kong-migrate:
        condition: service_completed_successfully

    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: host.docker.internal
      KONG_PG_PORT: 5432
      KONG_PG_DATABASE: kong
      KONG_PG_USER: postgres
      KONG_PG_PASSWORD: 1

      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000

    ports:
      - "8000:8000"
      - "8001:8001"