services:
  carts-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carts-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/carts_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATA_REDIS_HOST=host.docker.internal
      - SPRING_REDIS_PORT=6379
      - SPRING_RABBITMQ_HOST=host.docker.internal
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SPRING_APPLICATION_GATEWAY_ADMIN_URL=http://host.docker.internal:8001
