services:
  # Redis Service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - ecom-network

  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:4.2.4-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - ecom-network

  # Shared PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ecom-network

  # Kong Gateway Bootstrap
  kong-bootstrap:
    image: kong:3.6
    container_name: kong-bootstrap
    networks:
      - ecom-network
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_PORT: 5432
      KONG_PG_DATABASE: kong
      KONG_PG_USER: postgres
      KONG_PG_PASSWORD: postgres
    command: kong migrations bootstrap
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy

  # Kong Gateway Migrate
  kong-migrate:
    image: kong:3.6
    container_name: kong-migrate
    networks:
      - ecom-network
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_PORT: 5432
      KONG_PG_DATABASE: kong
      KONG_PG_USER: postgres
      KONG_PG_PASSWORD: postgres
    command: kong migrations up && kong migrations finish
    depends_on:
      kong-bootstrap:
        condition: service_completed_successfully
    restart: "no"

  # Kong Gateway
  kong:
    image: kong:3.6
    container_name: kong
    networks:
      - ecom-network
    depends_on:
      kong-migrate:
        condition: service_completed_successfully
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_PORT: 5432
      KONG_PG_DATABASE: kong
      KONG_PG_USER: postgres
      KONG_PG_PASSWORD: postgres
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    ports:
      - "8000:8000"
      - "8001:8001"

volumes:
  postgres-data:
  redis-data:
  rabbitmq-data:

networks:
  ecom-network:
    driver: bridge
